### PR TITLE
Implement get_attribute function for easy parsing

### PR DESCRIPTION
**Pull request by talha252**
With this function, I think parsing a new attribute will be easier. The only drawback is that currently the validation function only takes one argument or no argument. I didn't want to complicate things by implementing multi-parameter validation function since at least one argument is sufficient for us.

### CODE REVIEW

**Comment by uyaritu** [comment]
Did you run the tests, do they still pass?

Not that it's critical but, are you using black and pygenstub, or are you handling these manually?

**Comment by talha252** [comment]
Only `test_cli_version_should_print_version_number_and_exit` is failing right now but I don't it is related to my changes. 

I knew pygenstub previously, but I've just learned black. I reformatted the code with black.

**Comment by uyaritu** [comment]
Looks nice, merged. Thanks!

**Comment by uyaritu** [comment]
The version test doesn't fail on my setup.

**Comment by uyaritu** [comment]
Added your name to authors, feel free to change your entry in that file.

**Comment by talha252** [comment]
I think it fails because there is a conflict with my real env and the virtual env. Hope I figure it out soon.

**Comment by talha252** [comment]
Your name appears to be `viii. Turgut Uyar` on that file. I am not sure if this is correct.

**Comment by uyar** [comment]
Fixed the author name.

**Comment by uyar** [comment]
For the test error, you might need to reinstall calico. If you are using "pip install -e ." or "python setup.py develop", try re-running it. I prefer "pip install -e .[dev,doc,test]", or better still, poetry. I will probably move project packaging to poetry.

**Comment by talha252** [comment]
I love Python, I love coding with it but when it comes to the packaging or managing dependencies, it is so frustrating to see that there are many faulty (or insufficient, or convoluted) tools. I don't know it is me but I find it very agonizing to deal with these. By the way, I reinstall the Calico, now it seems to be working.

**Comment by talha252** [comment]
Hopefully, poetry will be the last tool for managing environments and packaging.

**Pull request merged**
