### PR TITLE
Make small corrections

### PR DESCRIPTION
**Pull request by Asocia**

### CODE REVIEW

**Comment by Asocia** [comment]
My IDE also shows a warning for `val_func`
image

When I change the signature from `Callable[[Any, ...], bool]` to `Callable[..., bool]` no more warnings given. But I didn't include this change since you are giving at most 2 arguments to `var_func` 
I tried `Callable[[Any, Optional[Any]], bool]` but it didn't work. So I left it as it is.

**Comment by uyaritu** [comment]
OK, nice contributions overall, thanks. Can you fix the trailing space issue? After that I'll merge your changes.

**Comment by Asocia** [comment]
Actually I was trying to understand what are all these classes that are derived from `Enum`. So I copy pasted the code to an interpreter but it didn't work because of blank line after docstring. So I deleted it but then forgot to put it back. Sorry for this.

**Comment by Asocia** [comment]
I will fix it when I'm on my computer. Hopefully this time I don't bring new errors.

**Comment by uyaritu** [comment]
No big deal. As I said, "black" can help you with this. Also, you can run "flake8 calico" to catch style issues. Or even better, install and run tox in the project directory to check whether everything is alright.

**Comment by Asocia** [comment]
@uyaritu I fixed the issue.

**Pull request merged**
